"""add_search_vector

Revision ID: 52fb7fef9c8f
Revises: d6045f12df88
Create Date: 2026-05-29 02:43:36.457973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52fb7fef9c8f'
down_revision: Union[str, None] = 'd6045f12df88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleries', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_gallery_search_vector', 'galleries', ['search_vector'], unique=False, postgresql_using='gin')
    
    op.execute("""
    CREATE OR REPLACE FUNCTION update_gallery_search_vector() RETURNS trigger AS $$
    BEGIN
      NEW.search_vector :=
         setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
         setweight(to_tsvector('english', coalesce(NEW.description, '')), 'B') ||
         setweight(to_tsvector('english', coalesce((
             SELECT string_agg(t.name, ' ')
             FROM gallery_tags gt
             JOIN tags t ON gt.tag_id = t.id
             WHERE gt.gallery_id = NEW.id
         ), '')), 'C');
      RETURN NEW;
    END
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
    ON galleries FOR EACH ROW EXECUTE FUNCTION update_gallery_search_vector();
    """)

    op.execute("""
    CREATE OR REPLACE FUNCTION update_gallery_search_vector_from_tags() RETURNS trigger AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        UPDATE galleries SET updated_at = NOW() WHERE id = OLD.gallery_id;
        RETURN OLD;
      ELSE
        UPDATE galleries SET updated_at = NOW() WHERE id = NEW.gallery_id;
        RETURN NEW;
      END IF;
    END
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER tsvectorupdate_tags AFTER INSERT OR UPDATE OR DELETE
    ON gallery_tags FOR EACH ROW EXECUTE FUNCTION update_gallery_search_vector_from_tags();
    """)

    # Populate existing data
    op.execute("UPDATE galleries SET updated_at = NOW()")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate_tags ON gallery_tags")
    op.execute("DROP FUNCTION IF EXISTS update_gallery_search_vector_from_tags()")
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON galleries")
    op.execute("DROP FUNCTION IF EXISTS update_gallery_search_vector()")
    op.drop_index('ix_gallery_search_vector', table_name='galleries', postgresql_using='gin')
    op.drop_column('galleries', 'search_vector')
